[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyAliceKit"
version = "0.1.0"
description = "Framework для создания диалоговых систем (Яндекс.Алиса, чат-боты)"
authors = [
    { name="Sergey", email="oborok05@bk.ru" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "Flask>=2.0",
    "typing-extensions>=4.0"
]

[project.urls]
Homepage = "https://github.com/sergey200519/pyAliceKit/"
